### PR TITLE
#32 Add conditional depenencies to reduce dependency graph

### LINKED ISSUE #32: Add additional TFM with less dependencies
### Describe the feature.
I want my application's and libraries to be as small as possible and the minimum amount of dependencies.

#### Is your feature related to a problem? 
Additional dependencies are being added to my projects.

#### Describe the requested feature

When the framework is able to natively provide a dependency ie System.* that should be utilised rather than an explicit dependency. This will be the case for the net 5+ TFM.
        
#### Describe alternatives you've considered
Accept the additional dependencies

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by thompson-tomo**
Added in conditional logic for dependencies so that 3 can be removed from the dependency graph  when targeting net5 or higher

Closes #32

### CODE REVIEW

**Comment by kubemq** [comment]
@thompson-tomo ,
I have to revert this merge because it breaks the code.
using System.Threading.Tasks.Dataflow is needed .

**Comment by thompson-tomo** [comment]
@kubemq  it is provided by the framework so u don't need an explicit dependency on it

**Comment by thompson-tomo** [comment]
Ahh, i worked out the issue. it looks like i did a typo after i tested which resulted in the condition not working as expected. Hence have resubmitted it.

**Comment by kubemq** [comment]
We are going to replace the BlockBuffer call with queue so no need for this
package at all

**Pull request merged**
